version: '3.8'
services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
    networks:
      - app-network

  spring-app:
    image: spring-ai-zoujiahui  # 改成你的镜像名
    container_name: spring-ai-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge